# Generated by Django 5.1.1 on 2024-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_info_email_alter_user_info_student_id'),
        ('general_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Enroll_by_user',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enroll_user',
        ),
        migrations.AddField(
            model_name='course',
            name='Enroll_by_user_info',
            field=models.ManyToManyField(related_name='Enroll_in_course', through='general_APP.Enrollment', to='app_user.user_info'),
        ),
    ]
