# Generated by Django 5.1.1 on 2024-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='student_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
