# Generated by Django 5.1.1 on 2024-10-19 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, upload_to='general_APP/files/covers')),
                ('lecturer', models.CharField(blank=True, max_length=60, null=True)),
                ('Info', models.TextField(blank=True, null=True)),
                ('Date_open', models.DateTimeField(null=True)),
                ('Date_close', models.DateTimeField(null=True)),
                ('Is_open', models.BooleanField(default=True)),
                ('Is_full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_pass', models.BooleanField(default=False)),
                ('enroll_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_APP.course')),
                ('enroll_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enroll_user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Enroll_by_user',
            field=models.ManyToManyField(related_name='Enroll_in_course', through='general_APP.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
